### ISSUE TITLE
outdated?

### ISSUE THREAD

**Issue by cgencer** [tomirons/laravel-accountant#3]
this package has been outdated as composer require reports conflicts:

Problem 1
    - Root composer.json requires tomirons/laravel-accountant ^1.1 -> satisfiable by tomirons/laravel-accountant[v1.1].
    - tomirons/laravel-accountant v1.1 requires illuminate/contracts 5.6.* -> found illuminate/contracts[v5.6.0, ..., 5.6.x-dev] but it conflicts with another require

are there any updates in sight? i am interested in using and experimenting with it. and does it support latest Stripe API changes?

**Comment by tomirons** [comment]
@cgencer you're more than welcome to create a PR to upgrade it to the latest version. 😀
